name: Manual Deployments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      os:
        description: 'Runner operating system'
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
      region:
        description: 'Azure region to deploy to'
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-west-2
          - eu-central-1
          - ap-northeast-1
      node_version:
        description: 'Specify the node version (e.g., 18)'
        required: true
        type: string
        default: 'latest'

jobs:
  deploy:
    runs-on: ${{ inputs.os  }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
