name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    outputs:
      js-filename: ${{ steps.publish-js-filename.outputs.js-filename }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: /var/www/html/
      - name: Publish JS filename
        id: publish-js-filename
        run: find dist/assets/*.js -type f -execdir echo 'js-filename={}' >> $GITHUB_OUTPUT' ';'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Output JS filename
        run: |
          echo "JS filename: ${{ needs.build.outputs.js-filename }}"
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-artifacts
      - name: Deploy
        run: echo "Deploying..."
